source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hientuong/PodSpec.git'

use_frameworks!

platform :ios, '13.0'

target 'AssistantUI_Example' do
  pod 'AssistantUI', '0.1.2'
#  pod 'AssistantAPI', '0.1.1'
#  pod 'Alamofire', '5.6.1'
#  pod 'RxCocoa', '~> 5.1'
  target 'AssistantUI_Tests' do
    inherit! :search_paths

    
  end
end
